version: "3"
services:

  frontend:
    build: packages/frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_NAME= Social Book
      - REACT_APP_RECAPTCHA_SITE_KEY= 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      - REACT_APP_RECAPTCHA_SECRET_KEY= 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    depends_on:
      - backend

  backend:
    build: packages/backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/live-chat
      - ACCESS_TOKEN_SECRET=secret
      - PORT=5000
      - CLOUDINARY_CLOUD_NAME=dxrhrbot0
      - CLOUDINARY_API_KEY=741876137836985
      - CLOUDINARY_API_SECRET=_FWECuyMeYfP0MbBSvAzTxknRoU
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
