version: "3"
services:

  frontend:
    build: packages/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: packages/backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      
volumes:
  mongodb-data:
