export const SET_FORM_SUBMITTING = 'SET_FORM_SUBMITTING';
export const SET_FORM_SUCCESS = 'SET_FORM_SUCCESS';
export const SET_FORM_FAILURE = 'SET_FORM_FAILURE';
export const SET_FORM_RESET = 'SET_FORM_RESET';

export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const SET_USER_LOGOUT = 'SET_USER_LOGOUT';

export const SET_APP_STATE_FETCHING = 'SET_APP_STATE_FETCHING';
export const SET_APP_STATE_SUCCESS = 'SET_APP_STATE_SUCCESS';
export const SET_APP_STATE_FAILURE = 'SET_APP_STATE_FAILURE';
export const SET_APP_STATE_DEFAULT = 'SET_APP_STATE_DEFAULT';

export const SET_POSTS= 'SET_POSTS';
