name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: path/to/image
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/image:${{ env.GITHUB_SHA }}
        tags: ${{ env.DOCKER_USERNAME }}/image:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_ACCESS_TOKEN }}

    - name: Push Docker Image
      uses: docker/push-action@v1
      with:
        tags: ${{ env.DOCKER_USERNAME }}/image:${{ env.GITHUB_SHA }}
        tags: ${{ env.DOCKER_USERNAME }}/image:latest
